server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
#        - id: payment_route  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/web/payment/hystrix/ok/**  # 断言，路径相匹配的进行路由
#
#        - id: payment_route2  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/web/payment/hystrix/timeout/**  # 断言，路径相匹配的进行路由

        - id: payment_route  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/web/payment/**  # 断言，路径相匹配的进行路由
            - After=2023-04-17T15:01:00.718+08:00[Asia/Shanghai]         # 断言，路径相匹配的进行路由
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
