server:
  port: 7001

# 单例
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己是注册中心，职责是维护服务实例，并不是去检索服务
    service-url: # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 集群
# 注意要需要改host文件
#  127.0.0.1       eureka7001.com
#  127.0.0.1       eureka7002.com
#eureka:
#  instance:
#    hostname: eureka7001.com # eureka服务端的实例名称
#  client:
#    register-with-eureka: false # false表示不向注册中心注册自己
#    fetch-registry: false # false表示自己是注册中心，职责是维护服务实例，并不是去检索服务
#    service-url: # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    enable-self-preservation: false # 关闭自我保护机制，保证不可用服务被及时剔除
#    eviction-interval-timer-in-ms: 2000