server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# 单例
eureka:
  client:
    register-with-eureka: true  # 表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka

# 集群
#eureka:
#  client:
#    register-with-eureka: true  # 表示是否将自己注册进EurekaServer默认为true
#    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001 # 主机名
#    prefer-ip-address: true #访问路径可以显示IP地址
#    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-expiration-duration-in-seconds: 2 # Eureka服务端在收到最后一次心跳等待时间上限，单位为秒（默认是90秒），超时将剔除服务